[project]
name = "py4ds"
version = "0.1.0"
description = "Programming in Python for Data Scientists"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pyright>=1.1.396",
    "pytest>=8.3.4",
]
