name: Pytest
on: [pull_request]
jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v5
      - name: Pytest
        env:
          PY4DS_PYTEST: 1
        run: uv run pytest
